CECS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("preinscripcion/",include("preinscripciones.urls")),
    path("",include("usuarios.urls_usuarios")),
    path("docentes/",include("usuarios.urls_docentes"))
] + static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

preinscripciones/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='preinscripciones'

urlpatterns = [
    #Aspirantes
    path('lista-aspirantes/', views.lista_aspirantes.as_view(), name='lista_aspirantes'),
    path('lista-aspirantes-rechazados/',views.lista_aspirantes_rechazados,name="lista_aspirantes_rechazados"),
    path('lista-aspirantes-aceptados/',views.lista_aspirantes_aceptados,name="lista_aspirantes_aceptados"),
    path('ver-aspirante/<int:pk>', views.ver_aspirante, name='ver_aspirante'),
    path("aceptar/<int:pk>",views.aceptar_aspirante, name="aceptar_aspirante"),
    path('rechazar/<int:pk>',views.rechazar_aspirante, name="rechazar_aspirante"),
    #Grupos
    path("lista-grupos/", views.ver_listas_grupos.as_view(), name="lista_grupos"),
    path("ver-grupo/<int:pk>",views.ver_grupo.as_view(), name="ver_grupo"),
    path('crear-grupo/', views.crearGrupo.as_view(), name="crear_grupo"),
    path('eliminar-grupo/<int:pk>', views.eliminarGrupo.as_view(), name="eliminar_grupo"),
    path("ver-lista-grupo/<int:pk>",views.ver_lista_alumnos_grupo, name="ver_aspirantes_grupo"),
    path("editar-grupo/<int:pk>",views.editarGrupo.as_view(),name="editar_grupo"),
    path("inscribirme/<int:pk_aspirante>/<int:pk_grupo>",views.inscribir_alumno_grupo, name="inscribir"),
    path("eliminar-aspirante-grupo/<int:pk>",views.eliminar_aspirante_grupo,name="eliminar_aspirante_grupo"),
    #Materias
    path("lista-materias/", views.lista_materias, name="lista_materias"),
    path("nueva-materia/", views.NuevaMateria.as_view(), name="nueva_materia"),
    path("eliminar-materia/<int:pk>",views.eliminar_materia.as_view(), name="eliminar_materia"),
    path("eliminar-materia-docente/<int:id_materia>/<int:id_docente>",views.eliminar_materia_docente, name="eliminar_materia_docente"),
    path("nueva-materia-docente/",views.NuevaMateriaDocente.as_view(),name="nueva_materia_docente"),
    path("ver-materia/<int:id>", views.ver_materia, name="ver_materia"),
    path("agregar-materia-grupo/",views.AgregarGrupoMateria.as_view(), name="agregar_materia_grupo"),
    path("ver-materias-grupo/<int:id>",views.verMateriasGrupo, name="ver_materias_grupo"),
    path("eliminar-grupo-materia-docente/<int:id_grupo>/<int:id_materia_docente>",views.eliminarGrupoMateriaDocente,name="eliminar_grupo_materia_docente"),
    path("editar-materia/<int:pk>",views.EditarMateria.as_view(),name="editar_materia")
]

preinscripciones/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

#Modelo referencial para el grupo
class Grupo(models.Model):
    letra = models.CharField(max_length = 1)
    cupo_limite=models.IntegerField('Cupo limite', validators=[MinValueValidator(1,MaxValueValidator(50))], default=40)
    cupo = models.IntegerField(blank=True, null=True)
    semestre= models.ForeignKey("preinscripciones.Semestre", verbose_name="Semestre", on_delete=models.CASCADE)
    horario=models.FileField(upload_to="", default=None, blank=True)
    def __str__(self):
        return self.letra

    def set_cupos_restantes(self,cupos_usados=0):
        self.cupo=self.cupo_limite - cupos_usados
        self.save()

class Grupo_Aspirante(models.Model):
    class Meta:
        unique_together=(("grupo","aspirante"),)
    grupo=models.ForeignKey("preinscripciones.Grupo", verbose_name="Grupo", on_delete=models.CASCADE)
    aspirante=models.ForeignKey("usuarios.Aspirante", verbose_name="Aspirante", on_delete=models.CASCADE)

#Modelo referencial para la materia
class Materia(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre

#Modelo referencial para el semestre
class Semestre(models.Model):
    numero=models.IntegerField('Semestre')
    def __str__(self):
        return str(self.numero)

#Modelo referencial para la relación de una materia con un grupo. Diseño para relaciones muchos a muchos.
class Grupo_materia(models.Model):
    grupo=models.ForeignKey("preinscripciones.Grupo", verbose_name="Grupo", on_delete=models.CASCADE)
    materia=models.ForeignKey("preinscripciones.Materia", verbose_name="Materia", on_delete=models.CASCADE)

#Modelo referencial para la relación de un docente con una materia. Diseño para relaciones muchos a muchos.
class Materia_docente(models.Model):
    class Meta:
        unique_together=(('materia','docente'),)
    materia = models.ForeignKey("preinscripciones.Materia", verbose_name = 'Materia', on_delete = models.CASCADE)
    docente = models.ForeignKey("usuarios.Docente", verbose_name = 'Docente', on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.materia.nombre+" - "+self.docente.last_name+" "+self.docente.first_name

#Modelo referencial para la relación de un docente que imparte una materia en un grupo específico. Diseño para relaciones muchos a muchos.
class Grupo_materia_docente(models.Model):
    class Meta:
        unique_together=(('materia_docente','grupo'),)
    materia_docente=models.ForeignKey("preinscripciones.Materia_docente", verbose_name="materia_docente", on_delete=models.CASCADE)
    grupo=models.ForeignKey("preinscripciones.Grupo",verbose_name="Grupo", on_delete=models.CASCADE)

preinscripciones/forms.py
from django import forms
from .models import Grupo, Materia, Grupo_materia_docente, Materia_docente

#Formulario para la creacion y edicion de grupos.
class GrupoForm(forms.ModelForm):
    class Meta:
        model=Grupo
        fields="letra", "cupo_limite","semestre","horario"

        widgets={
            'letra':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Grupo'}),
            'cupo_limite':forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Cupo máximo'}),
            'semestre':forms.Select(attrs={'class':'form-control', 'placeholder':'Semestre'})
        }

#Formulario para la creacion y edicion de materias.
class MateriaForm(forms.ModelForm):
    class Meta:
        model=Materia
        fields="__all__"

        widgets={
            "nombre":forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}),
            "descripcion":forms.TextInput(attrs={'class':'form-control', 'placeholder':'Descripcion'})
        }

#Formulario para la creacion y edicion de la relación de una materia con un docente (maestro).
class MateriaDocenteForm(forms.ModelForm):
    class Meta:
        model=Materia_docente
        fields="__all__"
        widgets={
            'materia':forms.Select(attrs={'class':'form-control','placeholder':"Materia"}),
            "docente":forms.Select(attrs={'class':'form-control', 'placeholder':'Docente'})
        }

#Formulario para la creacion y edicion de la relacion de un docente con una materia en un grupo en específico.
class GrupoMateriaDocenteForm(forms.ModelForm):
    class Meta:
        model=Grupo_materia_docente
        fields="__all__"
        widgets={
            "materia_docente":forms.Select(attrs={'class':'form-control', 'placeholder':'Materia'}),
            "grupo":forms.Select(attrs={'class':'form-control', 'placeholder':'Grupo'})
        }

preinscripciones/views.py
from django import http
from django.contrib import messages
from django.http import request
from .forms import GrupoForm, GrupoMateriaDocenteForm, MateriaDocenteForm, MateriaForm
from django.urls.base import reverse_lazy
from usuarios.models import Aspirante, Docente
from django.shortcuts import get_object_or_404, redirect, render
from .models import *
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

# Clase para visualizar la lista de aspirantes.
class lista_aspirantes(PermissionRequiredMixin,ListView):
    template_name='preinscripciones/list_aspirantes.html'
    model = Aspirante
    context_object_name="aspirantes"
    permission_required="auth.administrador_permiso"

# Funcion para visualizar la lista de aspirantes que han sido rechazados.
@permission_required('auth.administrador_permiso', raise_exception=True)
def lista_aspirantes_rechazados(request):
    lista_aspirantes=Aspirante.objects.filter(status=0)
    context={
        "aspirantes":lista_aspirantes
    }
    return render(request,"preinscripciones/list_aspirantes.html",context)

# Funcion para visualizar la lista de aspirantes que han sido aceptados.
@permission_required('auth.administrador_permiso', raise_exception=True)
def lista_aspirantes_aceptados(request):
    lista_aspirantes=Aspirante.objects.filter(status=1)
    context={
        "aspirantes":lista_aspirantes
    }
    return render(request,"preinscripciones/list_aspirantes.html",context)

# Funcion para visualizar a detalle los datos de un solo aspirante.
@permission_required('auth.administrador_permiso', raise_exception=True)
def ver_aspirante(request, pk):
    aspirante=get_object_or_404(Aspirante,id=pk)
    tipoDocumento=str(aspirante.comprobante_pago)[-3:]
    context={
        "aspirante":aspirante,
        "tipoDocumento":tipoDocumento
    }
    return render(request,"preinscripciones/detail_aspirante.html",context)

# Funcion que permite cambiar el estado de un aspirante a aceptado.
@permission_required('auth.administrador_permiso', raise_exception=True)
def aceptar_aspirante(request,pk):
    aspirante= get_object_or_404(Aspirante, id=pk)
    aspirante.status=1
    aspirante.is_active=True
    aspirante.save()
    enviar_correo_notificacion(pk)
    return redirect("preinscripciones:lista_aspirantes")

# Funcion para enviar un correo de notificación al aspirante cuando su cuenta para el sistema ha sido activada y ya puede iniciar sesión.
def enviar_correo_notificacion(pk):
    #Arreglar el envío de correo
    aspirante=Aspirante.objects.get(id=pk)
    mensaje =  render_to_string('aviso_aceptacion.html',
            {
                'aspirante' : aspirante
            }
        )
    asunto = 'Tu cuenta en CECS ha sido activada'
    correo = aspirante.email
    email = EmailMessage(
        asunto,
        mensaje,
        to=[correo]
    )
    email.content_subtype = 'html'
    email.send()

# Funcion que permite cambiar el estado de aceptado de un aspirante a no aceptado.
@permission_required('auth.administrador_permiso', raise_exception=True)
def rechazar_aspirante(request,pk):
    aspirante= get_object_or_404(Aspirante, id=pk)
    aspirante.status=0
    aspirante.is_active=False
    aspirante.save()
    return redirect("preinscripciones:lista_aspirantes")

# ---------------------- Grupos ----------------------------

# Clase para ver la lista de todos los grupos.
class ver_listas_grupos(PermissionRequiredMixin, ListView):
    permission_required="usuarios.aspirante_permiso"
    paginate_by = 5
    model = Grupo
    context_object_name="grupos"
    template_name='grupos/list_grupos.html'

# Clase para ver los datos a detalle de un grupo.
class ver_grupo(PermissionRequiredMixin, DetailView):
    permission_required="usuarios.aspirante_permiso"
    model = Grupo
    template_name="grupos/detalle.html"
    context_object_name='grupo'

# Clase que permite manejar el formulario de creación de un nuevo grupo.
class crearGrupo(PermissionRequiredMixin, CreateView):
    permission_required="auth.administrador_permiso"
    model=Grupo
    form_class=GrupoForm
    template_name="grupos/crear.html"
    success_url = reverse_lazy("preinscripciones:lista_grupos")

    def form_valid(self, form):
        form.instance.cupo=form.instance.cupo_limite
        return super(crearGrupo, self).form_valid(form)

# Clase que elimina un grupo en específico.
class eliminarGrupo(PermissionRequiredMixin, DeleteView):
    permission_required="auth.administrador_permiso"
    model = Grupo
    success_url = reverse_lazy('preinscripciones:lista_grupos')

# Clase que permite manejar los cambios de un formulario en un grupo existente.
class editarGrupo(PermissionRequiredMixin,UpdateView):
    permission_required="auth.administrador_permiso"
    model=Grupo
    form_class=GrupoForm
    template_name="grupos/editar.html"
    success_url=reverse_lazy("preinscripciones:lista_grupos")

# Funcion que permite ver la lista de alumnos en un grupo especifico.
@permission_required('usuarios.aspirante_permiso', raise_exception=True) #Nuevo permiso, para admin solamente
def ver_lista_alumnos_grupo(request,pk):
    grupoBusqueda=get_object_or_404(Grupo,id=pk)
    lista_aspirantes=Grupo_Aspirante.objects.filter(grupo=grupoBusqueda).values("aspirante","id")
    aspirantes=[]
    for aspirante in lista_aspirantes:
        aspirante_encontrado=get_object_or_404(Aspirante,id=aspirante['aspirante'])
        aspirante_encontrado.id_grupo_aspirante=aspirante['id']
        aspirantes.append(aspirante_encontrado)
    context={
        "aspirantes":aspirantes,
        "grupo":grupoBusqueda
    }
    return render(request,"grupos/list_aspirantes.html",context)

# Funcion que permite inscribir a un aspirante en un grupo.
@permission_required('usuarios.aspirante_permiso', raise_exception=True) #Cambiar el permiso, de momento está estático
#FALTA DE IMPLEMENTAR EN EL TEMPLATE Para que solamente los aspirantes se puedan inscribir
def inscribir_alumno_grupo(request, pk_aspirante, pk_grupo):
    aspirante=get_object_or_404(Aspirante, id=pk_aspirante)
    grupo=get_object_or_404(Grupo, id=pk_grupo)
    # Validacion para que se inscribia si solo tiene cupo.
    if(grupo.cupo<=0):
        messages.error(request,f'El grupo ya no tiene cupo')
        context={
            "messages":messages
        }
    elif(aspirante.grupo!=None): # Validacion para que si ya esta inscrito en algun grupo no se pueda inscribir en otro.
        messages.error(request,f'Ya estás inscrito en un grupo')
        context={
            "messages":messages
        }
    else:
        aspirante.grupo = grupo
        aspirante.save()
        Grupo_Aspirante.objects.create(grupo=grupo, aspirante=aspirante)
        cupos_usados=len(Grupo_Aspirante.objects.filter(grupo=grupo))
        grupo.set_cupos_restantes(cupos_usados=cupos_usados)
        messages.success(request,f'Inscrito correctamente en el grupo {grupo.letra}')
        context={
            "messages":messages
        }
    return redirect("preinscripciones:lista_grupos")

# ------------------------- Materias -----------------------------------------

# Clase que permite manejar el formulario para crear una nueva materia.
class NuevaMateria(PermissionRequiredMixin,CreateView):
    permission_required="auth.administrador_permiso"
    model=Materia
    form_class=MateriaForm
    template_name="materia/crear.html"
    success_url=reverse_lazy("preinscripciones:lista_materias")

# Clase que permite crear una relacion de una materia con su docente que la imparte.
class NuevaMateriaDocente(PermissionRequiredMixin,CreateView):
    permission_required="auth.administrador_permiso" #Nuevo permiso
    model=Materia_docente
    form_class=MateriaDocenteForm
    template_name="materia_docente/crear.html"
    success_url=reverse_lazy("preinscripciones:lista_materias")

# Metodo que permite ver la lista de materias con sus docentes que la imparten.
@permission_required("auth.administrador_permiso", raise_exception=True)
def lista_materias(request):
    materias=Materia.objects.all()
    for materia in materias:
        docentes_imparten=Materia_docente.objects.filter(materia=materia).values("docente")
        docentes=[]
        for docente in docentes_imparten:
            docenteEncontrado=Docente.objects.get(id=docente['docente'])
            docentes.append(docenteEncontrado)
        if len(docentes) != 0:
            materia.docentes=docentes
    context={
        "materias":materias
    }
    return render(request,"materia/lista.html",context)

# Metodo que permite ver los detalles de una materia en especifico.
@permission_required("usuarios.aspirante_permiso", raise_exception=True)
def ver_materia(request,id):
    materia=get_object_or_404(Materia,id=id)
    docentes_imparten=Materia_docente.objects.filter(materia=materia).values("docente")
    docentes=[]
    for docente in docentes_imparten:
        docenteEncontrado=Docente.objects.get(id=docente['docente'])
        docentes.append(docenteEncontrado)
    if len(docentes) != 0:
        materia.docentes=docentes
    context={
        "materia":materia
    }
    return render(request,"materia/detalle.html",context)

# Clase que permite crear una nueva relacion de un grupo con una materia impartida por un docente en especifico.
class AgregarGrupoMateria(PermissionRequiredMixin,CreateView):
    permission_required="auth.administrador_permiso"
    model=Grupo_materia_docente
    form_class=GrupoMateriaDocenteForm
    template_name="grupos/agregar_materia.html"
    success_url=reverse_lazy("preinscripciones:lista_grupos")

# Clase que permite manejar el formulario con los datos de una materia existente.
class EditarMateria(PermissionRequiredMixin,UpdateView):

preinscripciones/templates/aviso_aceptacion.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title> Confirmar cuenta</title>
  </head>
  <body>
    <div class="container">
        <div class="row propio-nav text-center">
            <div class="col">
                <h1>
                    Control Escolar Ciencias de la Salud CECS
                </h1>
                    
            </div>
        </div>
    <div class="row">
        <div class="col">
            <div >
                <h2>
                    Tu cuenta ha sido activada.
                </h2>
            </div>
            <div >
                <p>
                    Querido estudiante, te informamos que tu cuenta que registraste en la inscripcion del
                    semestre comun ha sido activada. <br>
                    Puedes accesar al sistema con tu usuario y contraseña para poder ver los grupos
                    y escoger el que más se acomode a tus necesidades, ver los detalles de los horarios e inscribirte en uno.
                </p>
                <p>
                    Sin más que decir, <strong>¡te esperamos!.</strong>
                </p>
                <hr>
                <p>
                    <h4>
                        Cordinacion de Ciencias de la Salud.
                    </h4>
                </p>
            </div>
        </div>
    </div>
    </div>
  </body>
</html>

preinscripciones/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        
        {% block css %}
          
        {% endblock css %}
        <title>
            {% block titulo %}
                
            {% endblock titulo %}
        </title>
    </head>
    <body>
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark propio-nav" style="margin-bottom: 0ex;">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Pre-inscripciones CECS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                {% if perms.auth.administrador_permiso %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Aspirante
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if perms.auth.administrador_permiso %}
                      <li><a class="dropdown-item" href="{% url 'preinscripciones:lista_aspirantes_aceptados' %}">Lista</a></li>
                      <li><a class="dropdown-item" href="{% url 'preinscripciones:lista_aspirantes' %}">Pendientes</a></li>
                      <li><a class="dropdown-item" href="{% url 'preinscripciones:lista_aspirantes_rechazados' %}">Rechazados</a></li>
                    {% endif %}
                  </ul>
                </li>
                {% endif %}
                
                
                
                {% if perms.auth.administrador_permiso %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Docente
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'docentes:lista_docentes' %}">Lista</a></li>
                    <li><a class="dropdown-item" href="{% url 'docentes:nuevo_docente'%}">Nuevo Docente</a></li>
                  </ul>
                </li>
                {% endif %}
                
                {% if perms.auth.administrador_permiso %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Materias
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'preinscripciones:lista_materias' %}">Lista</a></li>
                    <li><a class="dropdown-item" href="{% url 'preinscripciones:nueva_materia' %}">Nueva Materia</a></li>
                  </ul>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Grupos
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'preinscripciones:lista_grupos' %}">Lista</a></li>
                      {% if perms.auth.administrador_permiso %}
                        <li><a class="dropdown-item" href="{% url 'preinscripciones:crear_grupo' %}">Nuevo Grupo</a></li>
                      {% endif %}
                  </ul>
                </li>
              </ul>
              <!-- <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form> -->
            </div>
            <div>
              <a class="nav-link" aria-current="page" style="color:white" href="{% url 'usuarios:logout' %}">Cerrar sesión</a>
            </div>
          </div>
        </nav>

        <div class="separador container-fluid">
        </div>
    
        <div class="contenido">
          {% block contenido %}
          
          {% endblock contenido %}
        </div>
          
          <div class="separador container-fluid">
          </div>

        
        {% block js %}

        {% endblock js %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        
        
          
      </div>
      </body>
      </html>